global_frame: map
robot_base_frame: base_footprint
update_frequency: 3
publish_frequency: 2
always_send_full_costmap: false
static_map: true
rolling_window: false
origin_x: -5.0
origin_y: -5.0
plugins:
   - {name: static_layer, type: "rtabmap_ros::StaticLayer"}
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

