local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   update_frequency: 3.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   resolution: 0.05
   width: 4.0
   height: 4.0 
   origin_x:  -6.0
   oringin_y: -4.0
   transform_tolerance: 1.0
